# Generated by Django 5.2.4 on 2025-08-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0005_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="unenrolled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
