# Generated by Django 5.2.4 on 2025-08-19 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0012_alter_user_role_file_courselesson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courselesson",
            name="status",
        ),
        migrations.AddField(
            model_name="courselesson",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
