# Generated by Django 5.2.4 on 2025-08-21 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0018_coursefeedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursefeedback",
            name="rating",
            field=models.IntegerField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                validators=[
                    django.core.validators.MinValueValidator(
                        1, "Rating must be at least 1"
                    ),
                    django.core.validators.MaxValueValidator(
                        5, "Rating cannot exceed 5"
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="coursefeedback",
            name="text",
            field=models.TextField(
                validators=[
                    django.core.validators.MinLengthValidator(
                        10, "Feedback must be at least 10 characters"
                    ),
                    django.core.validators.MaxLengthValidator(
                        500, "Feedback cannot exceed 500 characters"
                    ),
                ]
            ),
        ),
    ]
