# Generated by Django 5.2.4 on 2025-08-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0024_add_description_to_chatroom"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="studentrestriction",
            index=models.Index(
                fields=["student", "course"],
                name="elearning_s_student_2ac76b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentrestriction",
            index=models.Index(
                fields=["student", "teacher", "course"],
                name="elearning_s_student_bcf02c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentrestriction",
            index=models.Index(
                fields=["teacher", "course"],
                name="elearning_s_teacher_cdf5f2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentrestriction",
            index=models.Index(
                condition=models.Q(("course__isnull", True)),
                fields=["student"],
                name="student_course_null_idx",
            ),
        ),
    ]
