# Generated by Django 5.2.4 on 2025-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "elearning",
            "0026_remove_notification_elearning_n_user_id_873059_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["chat_room", "created_at"],
                name="chat_messag_chat_ro_b6bf60_idx",
            ),
        ),
    ]
