# Generated by Django 5.2.4 on 2025-08-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0003_course"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="course",
            name="is_active",
        ),
        migrations.AddField(
            model_name="course",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
