# Generated by Django 5.2.4 on 2025-08-12 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0010_chatroom_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatroom",
            name="is_active",
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="chatparticipant",
            name="chat_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="elearning.chatroom",
            ),
        ),
    ]
