# Generated by Django 5.2.4 on 2025-08-19 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0014_alter_enrollment_course_alter_enrollment_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courselesson",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="elearning.file",
            ),
        ),
    ]
