# Generated by Django 5.2.4 on 2025-08-19 12:26

import elearning.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0015_alter_courselesson_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                storage=elearning.storage.PrivateCourseStorage(),
                upload_to="course_materials/%Y/%m/%d",
            ),
        ),
    ]
