# Generated by Django 5.2.4 on 2025-08-27 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0023_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
