# Generated by Django 5.2.4 on 2025-08-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0007_chatmessage_chatroom_chatparticipant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatparticipant",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("participant", "Participant")],
                default="participant",
            ),
        ),
    ]
