# Generated by Django 5.2.4 on 2025-08-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0008_alter_chatparticipant_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatroom",
            old_name="title",
            new_name="name",
        ),
    ]
