# Generated by Django 5.2.4 on 2025-08-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0009_rename_title_chatroom_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatroom",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
