# Generated by Django 5.2.4 on 2025-08-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elearning", "0021_studentrestriction_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentrestriction",
            name="reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
