# Generated by Django 5.2.4 on 2025-08-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0025_add_restriction_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='elearning_n_user_id_873059_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='elearning_n_user_id_f4b406_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentrestriction',
            name='elearning_s_student_2ac76b_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentrestriction',
            name='elearning_s_student_bcf02c_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentrestriction',
            name='elearning_s_teacher_cdf5f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentrestriction',
            name='student_course_null_idx',
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['chat_room', 'is_active'], name='chat_partic_chat_ro_8b98ca_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course', 'is_active', 'enrolled_at'], name='enrollments_course__0191bd_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='elearning_n_user_id_f64970_idx'),
        ),
        migrations.AddIndex(
            model_name='studentrestriction',
            index=models.Index(fields=['student', 'teacher'], name='elearning_s_student_cb4b70_idx'),
        ),
    ]
