# Generated by Django 5.2.1 on 2025-06-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bikeshop_project", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="list_price",
            new_name="price",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="list_price",
            new_name="price",
        ),
        migrations.RenameIndex(
            model_name="stock",
            new_name="bikeshop_pr_store_i_ba0857_idx",
            old_name="bikeshop_project__store_i_4c31b2_idx",
        ),
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
