# Generated by Django 5.2.1 on 2025-06-05 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "bikeshop_project",
            "0002_rename_list_price_orderitem_price_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="required_date",
            new_name="expected_delivery_date",
        ),
    ]
