# Generated by Django 5.2.1 on 2025-06-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bikeshop_project",
            "0003_rename_required_date_order_expected_delivery_date",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.IntegerField(
                choices=[
                    (1, "pending"),
                    (2, "processing"),
                    (3, "rejected"),
                    (4, "completed"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="bikeshop_project.order",
            ),
        ),
    ]
